# Generated by Django 3.0.6 on 2020-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_auto_20200505_0835'),
        ('illnesses', '0002_auto_20200505_0835'),
        ('recipes', '0002_auto_20200505_0835'),
        ('main', '0002_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AlterField(
            model_name='effect',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
