# Generated by Django 3.0.6 on 2020-05-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0005_remove_herb_ingredients'),
        ('main', '0005_illness_recipe_templatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='herb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herbs.Herb'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='illness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Illness'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Recipe'),
        ),
    ]
