# Generated by Django 3.0.6 on 2020-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200505_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatemodel',
            options={},
        ),
        migrations.AddConstraint(
            model_name='templatemodel',
            constraint=models.UniqueConstraint(fields=('herb', 'illness'), name='herb-illness'),
        ),
        migrations.AddConstraint(
            model_name='templatemodel',
            constraint=models.UniqueConstraint(fields=('herb', 'recipe'), name='herb-recipe'),
        ),
    ]
