# Generated by Django 3.0.6 on 2020-05-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200506_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='illness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Illness', verbose_name="My Best Staff's"),
        ),
    ]
