# Generated by Django 3.0.6 on 2020-05-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200507_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='illness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Illness'),
        ),
    ]
