# Generated by Django 3.0.6 on 2020-05-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200507_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraindication',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Contraindication'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Illness'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Recipe'),
        ),
    ]
