# Generated by Django 3.0.6 on 2020-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200507_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Substances')),
                ('percentage', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Substance',
                'verbose_name_plural': 'Substances',
            },
        ),
        migrations.AlterModelOptions(
            name='templatemodel',
            options={'verbose_name': 'Combination', 'verbose_name_plural': 'Combinations'},
        ),
        migrations.RemoveField(
            model_name='illness',
            name='description',
        ),
        migrations.RemoveField(
            model_name='illness',
            name='note',
        ),
    ]
