# Generated by Django 3.0.6 on 2020-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200518_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='impact',
            field=models.TextField(blank=True),
        ),
    ]
