# Generated by Django 3.0.6 on 2020-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='recipe_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='main.Recipe', verbose_name='recipe_image'),
        ),
    ]
