# Generated by Django 3.0.6 on 2020-05-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_imagemodel_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='illness_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilness_images', to='main.Illness', verbose_name='illness_image'),
        ),
    ]
