# Generated by Django 3.0.6 on 2020-05-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_imagemodel_illness_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='illness_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_images', to='main.Illness', verbose_name='illness_image'),
        ),
    ]
