# Generated by Django 2.2.12 on 2020-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200521_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
