# Generated by Django 3.0.6 on 2020-05-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herbs', '0002_herb_image'),
        ('main', '0002_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pieces', models.PositiveIntegerField(blank=True)),
                ('preparing', models.TextField()),
                ('note', models.TextField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Amount')),
                ('herbs', models.ManyToManyField(blank=True, to='herbs.Herb', verbose_name='herbs')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ImageModel')),
            ],
            options={
                'verbose_name': 'Illness',
                'verbose_name_plural': 'Illnesses',
                'ordering': ('title',),
            },
        ),
    ]
