# Generated by Django 3.0.6 on 2020-05-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0005_remove_herb_ingredients'),
        ('recipes', '0003_auto_20200505_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='herbs',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='value',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparing',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, choices=[('kg', 'kilograms'), ('g', 'grams'), ('ks', 'pieces'), ('dg', 'dekagrams')], max_length=5)),
                ('value', models.PositiveIntegerField(blank=True)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.Herb')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'verbose_name': 'Amount',
                'verbose_name_plural': 'Amounts',
                'abstract': False,
            },
        ),
    ]
