# Generated by Django 3.0.6 on 2020-05-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200505_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='herb',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeModel',
        ),
    ]
