# Generated by Django 3.0.5 on 2020-05-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('alternative_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('pieces', models.PositiveIntegerField(blank=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Amount')),
                ('contraindications', models.ManyToManyField(blank=True, null=True, to='main.Contraindication', verbose_name='contraindications')),
                ('effects', models.ManyToManyField(blank=True, null=True, to='main.Effect', verbose_name='effects')),
                ('ingredients', models.ManyToManyField(to='main.Ingredient', verbose_name='ingredients')),
            ],
            options={
                'verbose_name': 'Herb',
                'verbose_name_plural': 'Herbs',
                'ordering': ('title',),
            },
        ),
    ]
