# Generated by Django 3.0.6 on 2020-05-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagemodel'),
        ('herbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ImageModel'),
        ),
    ]
