# Generated by Django 3.0.6 on 2020-05-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_auto_20200505_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='herb',
            name='value',
        ),
    ]
