# Generated by Django 3.0.6 on 2020-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0004_auto_20200505_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='ingredients',
        ),
    ]
