# Generated by Django 3.0.6 on 2020-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200518_0811'),
        ('herbs', '0006_auto_20200507_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='batching',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='illnesses',
            field=models.ManyToManyField(blank=True, null=True, to='main.Illness', verbose_name='illnesses'),
        ),
        migrations.AddField(
            model_name='herb',
            name='latin_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='herb',
            name='substances',
            field=models.ManyToManyField(blank=True, null=True, to='main.Substance', verbose_name='substances'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='alternative_name',
            field=models.TextField(blank=True),
        ),
    ]
