# Generated by Django 3.0.6 on 2020-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0007_auto_20200518_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
