# Generated by Django 3.0.6 on 2020-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200518_0838'),
        ('herbs', '0008_auto_20200518_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='illnesses',
            field=models.ManyToManyField(blank=True, null=True, related_name='herb_illnesses', to='main.Illness', verbose_name='illnesses'),
        ),
    ]
