# Generated by Django 3.0.6 on 2020-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0010_auto_20200518_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
