# Generated by Django 2.2.12 on 2020-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0012_remove_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='alernative_name'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='batching',
            field=models.TextField(blank=True, verbose_name='batching'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='latin_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='latin_name'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='planting',
            field=models.TextField(blank=True, verbose_name='planting'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='video_link'),
        ),
    ]
